/* 
 * File:   mcal_interrupt_gen_config.h
 * Author: Rabeh Mohamed
 *
 * Created on August 2, 2023, 12:24 AM
 */

#ifndef MCAL_INTERRUPT_GEN_CONFIG_H
#define	MCAL_INTERRUPT_GEN_CONFIG_H

#define INTERRUPT_FEATURE_ENABLE 1U

#define EXTERNAL_INTERRUPT_INTx_FEATURE_ENABLE   INTERRUPT_FEATURE_ENABLE
#define EXTERNAL_INTERRUPT_OnChange_FEATURE_ENABLE   INTERRUPT_FEATURE_ENABLE
//#define INTERRUPT_PRIORITY_LEVELS_ENABLE    INTERRUPT_FEATURE_ENABLE



#endif	/* MCAL_INTERRUPT_GEN_CONFIG_H */

